### ISSUE TITLE
A quick question on tokenization of plain texts

### ISSUE THREAD

**Issue by zaemyung** [disrpt/sharedtask2021#5]
Hi,

I'd just like to ask, what tokenization tool (and its configuration) is used to generate the tokens in *.tok files?
Does it differ by language and frameworks?
I'm trying to apply the same preprocessing routine to raw plain strings for inference.

Thanks!

**Comment by amir-zeldes** [comment]
Hi - I'm happy to help figure it out, but as you suspected it depends on the data set and language. Datasets based on existing treebanks generally got the gold tokenization from the underlying resource (e.g. Wall Street Journal corpus, GUM), while for others, if no tokenization was available then automatic tools were used. If you tell me which dataset you're looking at I should be able to figure out the tool.

**Comment by zaemyung** [comment]
I'm mostly looking into English for now - PDTB and RST-DT mainly. I've looked at the manual for [PDTB 3.0](https://catalog.ldc.upenn.edu/docs/LDC2019T05/PDTB3-Annotation-Manual.pdf), but could not find the info about the tokenization. And on a related note, I've found [this page](https://notebook.community/arne-cl/alt-mulig/python/rstdt-fixing-tokenization) which seems to acknowledge the problem and do some custom tokenization.

**Comment by amir-zeldes** [comment]
I see - in the case of those datasets I can confirm the tokenization comes from manually annotated PTB itself (specifically actually the OntoNotes 5 version of the trees - notice there are hyphen tokens tagged HYPH, which did not exist in the original PTB). We converted the gold constituent trees using CoreNLP's deterministic conversion to Universal Dependencies, then we aligned the original EDUs (RST-DT)/argspans (PDTB) to the tokens, based on identical non-whitespace character content, and finally we introduced spaces corresponding exactly to that tokenization in the .rels files.

In other words, if you want to tokenize new data as similarly as possible, you should train a tokenizer (e.g. Stanza's) on OntoNotes 5 (ignoring traces and other empty tokens) and predict on your data. If your domain is not newswire though, I would recommend considering GUM as a basis, since PDTB and RST-DT are both exclusively from the WSJ news domain, and the textual data is quite old (~1990), so it doesn't mention a lot of contemporary concepts and words. If you do so, consider looking at the latest release of GUM, which has added new data and discourse relations since the 2021 shared task.

**Comment by zaemyung** [comment]
This is great! Thanks a lot for the detailed explanation and pointers to the resources.
